### ISSUE TITLE
YoloV5 EdgeTPU?

### ISSUE THREAD

**Issue by benlemond** [PINTO0309/PINTO_model_zoo#53]
General Question,

What are your thoughts and potentially your roadmap for an implementation of YoloV5 on the Coral edge TPU?

**Comment by PINTO0309** [comment]
To be honest, I wasn't too interested in a model with less performance than the YoloV4, but all variants were addressed and converted. I don't think it works properly, but it is committed.
**https://github.com/PINTO0309/PINTO_model_zoo/tree/master/059_yolov5/20_all**

- YoloV5s - EdgeTPU
![Screenshot 2020-12-02 21:55:36](https://user-images.githubusercontent.com/33194443/100876665-0887ab80-34eb-11eb-83e7-a5e072528e41.png)

**Comment by benlemond** [comment]
That's interesting.  I have a few questions.
1.  Assuming the full Yolov4/5 is too large to compile to the edgetpu, we must use Yolov4 tiny or yolov5s?
2.  Do you know of any links that compare v4-tiny vs. v4-s vs. v5s?
3.  I understood v5 to be approx. 10x smaller than than v4 with so similar mAP.  That is very useful.  However at that size is v5 still not small enough to compile completely to the tpu?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by PINTO0309** [comment]
>1.  Assuming the full Yolov4/5 is too large to compile to the edgetpu, we must use Yolov4 tiny or yolov5s?

First of all, the premise of issue setting is wrong. For a huge model, you can use a multi-TPU.
**https://coral.ai/docs/edgetpu/pipeline/#run-a-pipeline-with-c**

>2.  Do you know of any links that compare v4-tiny vs. v4-s vs. v5s?

Read the full text of the article, and all the images and videos.
**https://medium.com/swlh/yolov5-controversy-is-yolov5-real-20e048bebb08**

>3.  I understood v5 to be approx. 10x smaller than than v4 with so similar mAP.  That is very useful.  However at that size is v5 still not small enough to compile completely to the tpu?

I don't think it's a small model to rave about.
![Screenshot 2020-12-02 23:17:48](https://user-images.githubusercontent.com/33194443/100884282-a633a880-34f4-11eb-8e0d-a23ac1bcf634.png)

If I want accuracy and performance, I use the anchor-free NanoDet INT8 model for CPU inference instead of YOLO. I wouldn't use EdgeTPU in the first place because of the high cost.
**https://github.com/PINTO0309/PINTO_model_zoo/tree/master/072_NanoDet**

**Comment by pirazor** [comment]
Hello @PINTO0309, a new version of Yolov5 (v4) will be released soon. One of the developers shared the .pt file. They changed the Hardswish operations to Silu and they might be supported now in Tensorflow. I figured you would wanna give it a try.
[yolov5s4.pt](https://drive.google.com/uc?export=download&id=10UAvFXWktnAD223QGH0ECtsG9RLy_fIV)

**Comment by PINTO0309** [comment]
@pirazor 
I've converted YoloV5s v4 to saved_model, TFLite and TFJS. However, I don't understand how this model, which is no substitute for the previous one, can make me happy at all. If you want to convert to EdgeTPU anyway, please reduce the input resolution to 128x128 or 256x256 or smaller.
**https://github.com/PINTO0309/PINTO_model_zoo/tree/master/059_yolov5/21_yolov5s4**

**Comment by mosheliv** [comment]
@PINTO0309 can you please share the post processing code you used for the nanonet?

**Comment by JulianoEbram-Brz** [comment]
Hello, @PINTO0309 
I am trying to convert my custom yolov5s model to tflite, but converting is not good.
TPU Layer - 1, CPU Layer - 254
I am using very edgetpu_compiler version 5.
Please guide me in model converting with details.
Thank you.
